  version: "3"
  services:
    frontend:
      build: 
        context:  "./frontend"
        dockerfile: Dockerfile
      container_name: frontend-container
      ports:
        - 3000:3000
      stdin_open: true
      tty: true    
      depends_on:
        - backend
      networks:
        - foods-network
      volumes:
        - ./frontend:/app
    backend:
      build:
        context: "./backend"
        dockerfile: Dockerfile
      container_name: backend-container
      restart: always
      env_file:
        - ./backend/.env
      ports:
        - 5000:5000
      stdin_open: true
      tty: true    
      depends_on:
        - mongo
      environment:
        - DB_HOST=MONGODB_HOST
        - DB_USER=MONGODB_USER
        - DB_PASSWORD=MONGODB_PASSWORD
        - DB_NAME=MONGODB_DATABASE
        - DB_PORT=MONGODB_DOCKER_PORT
      networks:
        - foods-network
      volumes:
        - ./backend:/app
    mongo:
      image: "mongo:4.0"  
      container_name: mongo-container
      ports:
        - 27017:27017
      volumes:
        - mongoData:/data/db
      networks:
        - foods-network
      env_file:
        - ./backend/.env
     
     
      
    
   
          

  networks:
    foods-network:
      driver: bridge

  volumes:
    mongoData:
      

    
